import math
from xml.sax.saxutils import escape


def render(drawing_ir):
    sheet = drawing_ir["sheet"]
    sheet_attrs = [
        'id="sheet"',
        f'data-format="{escape_attr(sheet["format"])}"',
    ]
    if sheet.get("standard"):
        sheet_attrs.append(f'data-standard="{escape_attr(sheet["standard"])}"')
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            '<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{fmt(sheet["width_mm"])}mm" '
            f'height="{fmt(sheet["height_mm"])}mm" '
            f'viewBox="0 0 {fmt(sheet["width_mm"])} {fmt(sheet["height_mm"])}">'
        ),
        f'  <title>{escape_text(drawing_ir["source_job_id"])}</title>',
        '  <desc>Generated by blueprints_backend from DrawingIR 1.0</desc>',
        f'  <g {" ".join(sheet_attrs)}>',
    ]

    layers = {layer["id"]: layer for layer in drawing_ir["layers"]}
    for element in drawing_ir.get("sheet_elements", []):
        lines.append(render_sheet_element(element, layers[element["layer"]]))
    for view in drawing_ir["views"]:
        lines.append(f'    <g id="view-{escape_attr(view["id"])}" data-scale="{fmt(view["scale"])}">')
        for entity in view["entities"]:
            if entity["type"] == "line":
                lines.append(render_line(view, entity, layers[entity["layer"]]))
        lines.append("    </g>")

    lines.extend(["  </g>", "</svg>", ""])
    return "\n".join(lines)


def render_sheet_element(element, layer):
    if element["type"] == "rect":
        return render_rect(element, layer)
    if element["type"] == "line":
        return render_absolute_line(element, layer)
    if element["type"] == "text":
        return render_text(element, layer)
    raise ValueError(f"Unsupported sheet element type {element['type']}.")


def render_rect(element, layer):
    attrs = [
        f'id="{escape_attr(element["id"])}"',
        f'x="{fmt(element["x_mm"])}"',
        f'y="{fmt(element["y_mm"])}"',
        f'width="{fmt(element["width_mm"])}"',
        f'height="{fmt(element["height_mm"])}"',
        'fill="none"',
        f'stroke="{layer["stroke"]}"',
        f'stroke-width="{fmt(layer["stroke_width"])}"',
    ]
    return f'    <rect {" ".join(attrs)} />'


def render_absolute_line(element, layer):
    return render_line_coordinates(
        element["id"],
        element["start_mm"][0],
        element["start_mm"][1],
        element["end_mm"][0],
        element["end_mm"][1],
        layer,
        indent="    ",
    )


def render_text(element, layer):
    attrs = [
        f'id="{escape_attr(element["id"])}"',
        f'x="{fmt(element["x_mm"])}"',
        f'y="{fmt(element["y_mm"])}"',
        f'font-size="{fmt(element["font_size_mm"])}"',
        f'font-family="{escape_attr(element["font_family"])}"',
        f'fill="{layer["fill"]}"',
    ]
    return f'    <text {" ".join(attrs)}>{escape_text(element["text"])}</text>'


def render_line(view, entity, layer):
    x1, y1 = transform(view, entity["start_mm"])
    x2, y2 = transform(view, entity["end_mm"])
    return render_line_coordinates(entity["id"], x1, y1, x2, y2, layer, indent="      ")


def render_line_coordinates(element_id, x1, y1, x2, y2, layer, indent):
    attrs = [
        f'id="{escape_attr(element_id)}"',
        f'x1="{fmt(x1)}"',
        f'y1="{fmt(y1)}"',
        f'x2="{fmt(x2)}"',
        f'y2="{fmt(y2)}"',
        'fill="none"',
        f'stroke="{layer["stroke"]}"',
        f'stroke-width="{fmt(layer["stroke_width"])}"',
        'stroke-linecap="round"',
    ]
    if "stroke_dasharray" in layer:
        attrs.append(f'stroke-dasharray="{layer["stroke_dasharray"]}"')
    return f'{indent}<line {" ".join(attrs)} />'


def transform(view, point):
    return [
        view["origin_mm"][0] + point[0] * view["scale"],
        view["origin_mm"][1] + point[1] * view["scale"],
    ]


def fmt(value):
    if isinstance(value, int):
        return str(value)
    if not math.isfinite(float(value)):
        raise ValueError("SVG numeric values must be finite.")
    if float(value).is_integer():
        return str(int(value))
    return f"{value:.6f}".rstrip("0").rstrip(".")


def escape_text(value):
    return escape(str(value))


def escape_attr(value):
    return escape(str(value), {'"': '&quot;'})
