import math
from xml.sax.saxutils import escape


def render(drawing_ir):
    sheet = drawing_ir["sheet"]
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            '<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{fmt(sheet["width_mm"])}mm" '
            f'height="{fmt(sheet["height_mm"])}mm" '
            f'viewBox="0 0 {fmt(sheet["width_mm"])} {fmt(sheet["height_mm"])}">'
        ),
        f'  <title>{escape_text(drawing_ir["source_job_id"])}</title>',
        '  <desc>Generated by blueprints_backend from DrawingIR 1.0</desc>',
        f'  <g id="sheet" data-format="{escape_attr(sheet["format"])}">',
    ]

    layers = {layer["id"]: layer for layer in drawing_ir["layers"]}
    for view in drawing_ir["views"]:
        lines.append(f'    <g id="view-{escape_attr(view["id"])}" data-scale="{fmt(view["scale"])}">')
        for entity in view["entities"]:
            if entity["type"] == "line":
                lines.append(render_line(view, entity, layers[entity["layer"]]))
        lines.append("    </g>")

    lines.extend(["  </g>", "</svg>", ""])
    return "\n".join(lines)


def render_line(view, entity, layer):
    x1, y1 = transform(view, entity["start_mm"])
    x2, y2 = transform(view, entity["end_mm"])
    attrs = [
        f'id="{escape_attr(entity["id"])}"',
        f'x1="{fmt(x1)}"',
        f'y1="{fmt(y1)}"',
        f'x2="{fmt(x2)}"',
        f'y2="{fmt(y2)}"',
        'fill="none"',
        f'stroke="{layer["stroke"]}"',
        f'stroke-width="{fmt(layer["stroke_width"])}"',
        'stroke-linecap="round"',
    ]
    if "stroke_dasharray" in layer:
        attrs.append(f'stroke-dasharray="{layer["stroke_dasharray"]}"')
    return f'      <line {" ".join(attrs)} />'


def transform(view, point):
    return [
        view["origin_mm"][0] + point[0] * view["scale"],
        view["origin_mm"][1] + point[1] * view["scale"],
    ]


def fmt(value):
    if isinstance(value, int):
        return str(value)
    if not math.isfinite(float(value)):
        raise ValueError("SVG numeric values must be finite.")
    if float(value).is_integer():
        return str(int(value))
    return f"{value:.6f}".rstrip("0").rstrip(".")


def escape_text(value):
    return escape(str(value))


def escape_attr(value):
    return escape(str(value), {'"': '&quot;'})
